# Generated by Django 4.2 on 2024-09-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='images_imag_total_l_0bcd7e_idx',
        ),
        migrations.AlterField(
            model_name='image',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
